### ISSUE TITLE
Pataisyti talentų puslapių turinį

### ISSUE THREAD

**Issue by dainiusjocas** [dainiusjocas/si#30]
- [x] Duplikuotas turinys https://www.jocas.lt/si/talentai/2015/ ir https://www.jocas.lt/si/talentai/2018/
- [x] Jeigu ko nors trūksta pridėti prie talentų puslapių iš https://www.jocas.lt/si/informacija/talentai/
- [x] Ar dar reikalingas šitas puslapis https://www.jocas.lt/si/informacija/talentai/

**Comment by GGutparakyte** [comment]
pataisiau duplikuotą turinį.
